theme: jekyll-theme-minimal
title: "Finding the next Lord of the Rings: From Book to Cinematic Glory"
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  - title: Test Plot
    url: test_plot
